name: CI Sanity
on:
  push:
    branches: [ main, AutomaticImports ]
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello from $GITHUB_REF on ${{ github.repository }}!"